version: '3.8'
services:
  mongo:
    image: mongo:6
    container_name: bbsneo-mongo
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: bbsneo-redis
    ports: ["6379:6379"]

  minio:
    image: minio/minio:latest
    container_name: bbsneo-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: bbsneo-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  minio_data:
  qdrant_data: